imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        [ 'goBundle']
    #java: /usr/bin/java
    filters:
        less:
          node: /usr/bin/nodejs
          node_paths: [/usr/lib/node_modules]
          apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        bootstrap__js:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/js/bootstrap.js
        bootstrap__css:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/../vendor/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]
        bootstrap__glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap__glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap__glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap__glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        jquery_js:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/dist/jquery.js
        angularjs:
            inputs:
                - %kernel.root_dir%/../vendor/angular/angular.js
        d3_js:
            inputs:
                - %kernel.root_dir%/../vendor/d3/d3.js
        angular_route:
            inputs:
                - %kernel.root_dir%/../vendor/angular-route/angular-route.js
        angular_ressource:
            inputs:
                - %kernel.root_dir%/../vendor/angular-resource/angular-resource.js
        nvd3_js:
            inputs:
                - %kernel.root_dir%/../vendor/nvd3/build/nv.d3.js
        nvd3_css:
            inputs:
                - %kernel.root_dir%/../vendor/nvd3/build/nv.d3.css
        angular_nvd3_js:
            inputs:
                - %kernel.root_dir%/../vendor/angularjs-nvd3-directives/dist/angularjs-nvd3-directives.js
        angular_bootstrap:
            inputs:
                - %kernel.root_dir%/../vendor/angular-bootstrap/ui-bootstrap-tpls.js
        angular_animate:
            inputs:
                - %kernel.root_dir%/../vendor/angular-animate/angular-animate.js
                
#tbbc_money:
#    currencies: ["USD", "EUR"]
#    reference_currency: "EUR"
#    decimals: 2   




# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
