security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Hager\TransformationBundle\Entity\User: plaintext

    providers:
        chain_providers:
            chain:
                providers:  [main, in_memory]
        main:
            entity:
                { class: Hager\TransformationBundle\Entity\User, property: username }
        in_memory:
            memory:
                users:
                    reporter:  { password: reporterpass, roles: [ 'ROLE_REPORTER' ] }
                    supervisor: { password: supervisorpass, roles: [ 'ROLE_SUPERVISOR' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        default:
            pattern:  ^/
            anonymous:  true
            http_basic: ~
            form_login:
                login_path: transformation_home
                check_path: login_check
                default_target_path: login_success
            logout:
                path: logout
                target: transformation_home
                
                

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/application/supervisor/, roles: ROLE_SUPERVISOR}
        - { path: ^/application/reporter/, roles: ROLE_REPORTER}
        - { path: ^/application, roles: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/api/, roles: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/login_success, roles: IS_AUTHENTICATED_REMEMBERED}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        
        
        
        
        