services:
    transformation.carto_loader:
        class:  Hager\TransformationBundle\Service\CartographyManager
#    transformation.example:
#        class: Hager\TransformationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
