services:
    transformation.carto_loader:
        class:  Hager\TransformationBundle\Service\CartographyManager
        
    transformation.reporter_manager:
        class:  Hager\TransformationBundle\Service\ReporterManager
        arguments:  [@request_stack, @transformation.reporter_repository]
        
    transformation.reporter_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - Hager\TransformationBundle\Entity\Reporter
            
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
#    transformation.example:
#        class: Hager\TransformationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
