services:
    transformation.action_plan:
        class:  Hager\TransformationBundle\Service\ActionPlanService
#    transformation.example:
#        class: Hager\TransformationBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
