services:
    go.form.type.adjustOrdoItem:
        class: exxan\maquetteBundle\Form\AdjustOrdoItemType
        tags:
            - { name: form.type, alias: AdjustOrdoItem }

#        arguments: [@service_id, "plain_value", %parameter%]